### ISSUE TITLE
code_bundesland

### ISSUE THREAD

**Issue by ckluss** [sumtxt/ags#1]
thx for providing the package!

In version 1.0.0 the default seems to be

`ags::code_bundesland(sourcevar, origin = "name", destination = "ags", factor = FALSE) `

instead of

`ags::code_bundesland(sourcevar, origin = "ags", destination = "name", factor = FALSE) `

Best wishes
Christof

**Comment by sumtxt** [comment]
Thank you for reporting. This has been fixed. 6cbfb5d2ec9c1aec5bdecc1776973c78323f33e1
